use customer_behaviour;
select * from customer limit 10;

-- Total revenue generated by male vs female customer?
select gender , sum(purchase_amount) as revenue 
from customer
group by gender ;

# customer used a discount but still spent more than the average purchase amount ?
 select customer_id,purchase_amount
 from customer 
 where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer);
 
 # which are the top 5 products with the highest wvg review rating??
 select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
 from customer 
 group by item_purchased
 order by avg(review_rating) desc
 limit 5 ;
 
 # compare avg purchase amounts between standard and express shipping ??
 select shipping_type,
 ROUND(AVG(purchase_amount),2)
 from customer 
 where shipping_type in ('Standard', 'Express')
 group by shipping_type;
 
 #  Do subscribed customers spend more? Compare average spend and total revenue 
#between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue, avg_spend desc;

#Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;

# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5 
group by subscription_status;


DROP USER IF EXISTS 'powerbi'@'localhost';
CREATE USER 'powerbi'@'localhost' 
IDENTIFIED WITH 
mysql_native_password BY 'PowerBI123';

GRANT ALL PRIVILEGES ON *.* TO 'powerbi'@'localhost';
FLUSH PRIVILEGES;